name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rake
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Setup SSH
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts
          touch ~/.ssh/id_rsa
          chmod -R 700 ~/.ssh
      - name: Add SSH key
        run: echo "${{ secrets.SHRT_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      - name: Scan server keys
        run: ssh-keyscan jon.zone >> ~/.ssh/known_hosts
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Deploy site
        env:
          DEPLOY_TARGET: ${{ secrets.DEPLOY_TARGET }}
        run: bundle exec rake deploy
